{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.libxposed",
    "module": "service",
    "version": "100-13-g496b76f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "service-100-13-g496b76f.aar",
          "url": "service-100-13-g496b76f.aar",
          "size": 16031,
          "sha512": "97f8b0818088d76dfdbdde07db74f2dc70f10948659d5d5e8b52a9e9525534aa2c84147dcbf52df03594fe972867ebd2eb5545ddbda3accdf2c2bb13b4a33b19",
          "sha256": "4042789a8b0fc23a11183a6b364adb00a533965dc052d163ae760f14ef080905",
          "sha1": "cf181ac564173b239c33a26f638d2eceb784a77b",
          "md5": "40d76f1f6b5ffe9b52bd29aa3dbcd764"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.libxposed",
          "module": "interface",
          "version": {
            "requires": "100-13-g496b76f"
          }
        }
      ],
      "files": [
        {
          "name": "service-100-13-g496b76f.aar",
          "url": "service-100-13-g496b76f.aar",
          "size": 16031,
          "sha512": "97f8b0818088d76dfdbdde07db74f2dc70f10948659d5d5e8b52a9e9525534aa2c84147dcbf52df03594fe972867ebd2eb5545ddbda3accdf2c2bb13b4a33b19",
          "sha256": "4042789a8b0fc23a11183a6b364adb00a533965dc052d163ae760f14ef080905",
          "sha1": "cf181ac564173b239c33a26f638d2eceb784a77b",
          "md5": "40d76f1f6b5ffe9b52bd29aa3dbcd764"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "service-100-13-g496b76f-sources.jar",
          "url": "service-100-13-g496b76f-sources.jar",
          "size": 6432,
          "sha512": "5bb3dacf63ea297fb4fcdc30df604a0f464e9dd36a77c7fe8d85e891d8fe55da1ae2230034d0df56cc2ad52642e1a23e954a021d30a8ef062910f33291101b46",
          "sha256": "a9a4e7701e88935b05de2c9239a4d8de1c1ea1a2dda43a00ad3978ba77f31cbd",
          "sha1": "5d0910b8071ea2f664b9cd155ca17a0641c1de93",
          "md5": "1abbf6b16be7d25061297ef34a8c19a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "service-100-13-g496b76f-javadoc.jar",
          "url": "service-100-13-g496b76f-javadoc.jar",
          "size": 320622,
          "sha512": "47d70a0276affb086f5d3975b24af465571a4f2984ae4b3b89264b284e18c961375ae8f320edec9a49d19164b52e95501565615cf7083930f98ddefa327e0173",
          "sha256": "de8413568c54447f2e34af169aba14459d2be3da32aade91eb9feb5a2ac6e421",
          "sha1": "893e0da9d2e27a9846ebf7a0de8b420ff5026df5",
          "md5": "525b3a9515c1c08982aecb096c7e3d91"
        }
      ]
    }
  ]
}
