{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.libxposed",
    "module": "interface",
    "version": "100-13-g496b76f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "interface-100-13-g496b76f.aar",
          "url": "interface-100-13-g496b76f.aar",
          "size": 12239,
          "sha512": "c2444f40e3df53cec9add3af83eaae7551841ac00d262eaaa1dd8f1a1ab43b8588ef5f0c45acd81d81b3b4edcc99dd0e69d53c0e41e19b828f1b2cfe1fba7b25",
          "sha256": "55adeda9f44b290da16621db86f3bc9f649cfba6a33c4193cbf8e05dd0952c67",
          "sha1": "625e7eabbab3b1da3a5b428900dbc92bbeec0b5e",
          "md5": "47b9276cd1062446cd6ce5721aa4990f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interface-100-13-g496b76f.aar",
          "url": "interface-100-13-g496b76f.aar",
          "size": 12239,
          "sha512": "c2444f40e3df53cec9add3af83eaae7551841ac00d262eaaa1dd8f1a1ab43b8588ef5f0c45acd81d81b3b4edcc99dd0e69d53c0e41e19b828f1b2cfe1fba7b25",
          "sha256": "55adeda9f44b290da16621db86f3bc9f649cfba6a33c4193cbf8e05dd0952c67",
          "sha1": "625e7eabbab3b1da3a5b428900dbc92bbeec0b5e",
          "md5": "47b9276cd1062446cd6ce5721aa4990f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interface-100-13-g496b76f-sources.jar",
          "url": "interface-100-13-g496b76f-sources.jar",
          "size": 4792,
          "sha512": "e26f625cabb9767b3f217caae5d238781e72c64172f9150ce09629abaae04ab55189da72b4ff730b4ed14f07f3f09dc29333e6706e4d97f0ee7e2ef33c5dd1ca",
          "sha256": "09c70289219f22e6305daed985fd7934b99989395ac108277f24c7c11c5e3cbc",
          "sha1": "58c03cc7c655020d4f9417b3cbe40103046234af",
          "md5": "c2f07a3259b0df52161648b20fc63b4c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interface-100-13-g496b76f-javadoc.jar",
          "url": "interface-100-13-g496b76f-javadoc.jar",
          "size": 307174,
          "sha512": "7212c91cf38f1cb0663218f3e5dc7a9a2e27912cd61a915b8aa01a39815f7957b47b7f7725f3a8d2bacb2c4c11cc7ca9914539081a9bca7e411feaf0e64aab4d",
          "sha256": "9b5e5fed5ad37b01a844c419ead48c19556be74012d85e8f72f9736b58fb2324",
          "sha1": "bcc117a08f7cc271a33552173b2734060407220f",
          "md5": "dd96fb0a16f0e9adb13360cc850b7484"
        }
      ]
    }
  ]
}
